# name: Deploy to EC2

# on:
#   push:
#     branches:
#       - dev

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '20'

#       - name: Build app
#         run: |
#           npm ci
#           npm run build

#       - name: Deploy to EC2
#         uses: appleboy/ssh-action@v0.1.9
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USER }}
#           key: ${{ secrets.EC2_SSH_KEY }}
#           script: |
#             cd /home/ubuntu/etihad-bus-backend || git clone git@github.com:mohamedsherif95/etihad-bus-backend.git /home/ubuntu/etihad-bus-backend
#             cd /home/ubuntu/etihad-bus-backend
#             git pull origin dev
#             npm install
#             npm run build
#             pm2 restart etihad-bus-backend || pm2 start dist/main.js --name etihad-bus-backend
